# ----------------------------------------------------
# OptiCore | Optimized Server Pack
# Main Skript, Use With Caution.
# ----------------------------------------------------

function loadOCConfig():
    load yaml "plugins/OptiCore/OptiCore.yml" as "oc.config"
    wait 1 tick
    
    if yaml "oc.config" is loaded:
        set {oc::auto_clearlag} to yaml value "features.auto_clearlag" from "oc.config"
        
        # Load Gamerules
        set {_cramming} to yaml value "gamerules.max_entity_cramming" from "oc.config"
        
        # Apply Gamerules
        loop all worlds:
            if {_cramming} is set:
                execute console command "gamerule max_entity_cramming %{_cramming}%"
        
        send "[OptiCore] Configuration loaded and applied." to console
    else:
        send "[OptiCore] ERROR: Could not load OptiCore.yml" to console

on skript load:
    wait 5 seconds
    loadOCConfig()

# --- AUTO CLEARLAG TIMER ---
every 15 minutes:
    if {oc::auto_clearlag} is true:
        execute console command "oc purge"
        broadcast "&b[OptiCore] &fAutomatic lag clearing complete."

# ---TAB COMPLETION ---
on tab complete of "/opticore":
    set tab completions for position 1 to "reload", "purge", "link", and "tps"

on tab complete of "/oc":
    set tab completions for position 1 to "reload", "purge", "link", and "tps"

# --- COMMANDS ---
command /opticore [<text>]:
    aliases: /oc
    permission: opticore.admin
    trigger:
        if arg-1 is "reload":
            loadOCConfig()
            send "&a[OptiCore] &fConfig reloaded."
        else if arg-1 is "purge":
            kill all dropped items
            kill all xp orbs
            kill all monsters
            send "&e[OptiCore] &fCleanup complete."
        else if arg-1 is "tps":
            send "&bOptiCore &rSystem Monitor"
            send "&7TPS: &a%tps from last 1 minute%"
            execute player command "mspt"
        else if arg-1 is "link":
            send "&b&lOptiCore &f&lWebsites:"
            send formatted "<tooltip:Click To Get Redirected!><link:https://sites.google.com/view/opticoremc/main>&b&l>> Website" to player
            send formatted "<tooltip:Click To Get Redirected!><link:https://github.com/firesmasher-c6/OptiCore>&b&l>> Github" to player

command /startclearlag:
    permission: opticore.admin
    trigger:
        set yaml value "features.auto_clearlag" from "oc.config" to true
        save yaml "oc.config"
        set {oc::auto_clearlag} to true
        send "&b[OptiCore] &fAutomatic Clearlag &aENABLED&f."

command /stopclearlag:
    permission: opticore.admin
    trigger:
        set yaml value "features.auto_clearlag" from "oc.config" to false
        save yaml "oc.config"
        set {oc::auto_clearlag} to false
        send "&b[OptiCore] &fAutomatic Clearlag &cDISABLED&f."

command /clearlag:
    permission: opticore.admin
    trigger:
        execute player command "/oc purge"
        send "&b&lOptiCore &rCompleted Task (clearlag)"

command /tps:
    permission: opticore.admin
    trigger:
        execute player command "/oc tps"

command /discord:
    trigger:
        send formatted "<tooltip:Join Our Discord!><link:https://discord.gg/YOUR_LINK_HERE>Hello! If You're Seeing This. This still dont have a link please configure it at plugins/Skript/scripts/OptiCore.sk, Change YOUR_LINK_HERE with your link"
# Hey! You configure this /discord! Nothing will be broken!

# --- ESSENTIALS ---
on join:
    if player is op:
        execute player command "version"

on load:
    broadcast "&8&l[&b&lOptiCore&8&l] &rFinished Reloading Main Skript"